In [1]:
import pandas as pd

In [5]:
users=pd.read_csv('users.csv')

In [ ]:
users.head(10)

   id         user_name          password
0   1    vance.jennings          joobheco
1   2    consuelo.eaton        0869347314
2   3   mitchel.perkins        fabypotter
3   4    odessa.vaughan         aharney88
4   5    araceli.wilder        acecdn3000
5   6  shawn.harrington           5278049
6   7        evelyn.gay            master
7   8       noreen.hale            murphy
8   9       gladys.ward           lwsves2
9  10   brant.zimmerman  1190KAREN5572497

In [7]:
# Calculating the lengths of users' passwords
import pandas as pd
users = pd.read_csv('users.csv')
users['length'] = users.password.str.len()
users['too_short'] = users['length'] < 8
print(users['too_short'].sum())

# Taking a look at the 12 first rows
users.head(12)

376

    id         user_name          password  length  too_short
0    1    vance.jennings          joobheco       8      False
1    2    consuelo.eaton        0869347314      10      False
2    3   mitchel.perkins        fabypotter      10      False
3    4    odessa.vaughan         aharney88       9      False
4    5    araceli.wilder        acecdn3000      10      False
5    6  shawn.harrington           5278049       7       True
6    7        evelyn.gay            master       6       True
7    8       noreen.hale            murphy       6       True
8    9       gladys.ward           lwsves2       7       True
9   10   brant.zimmerman  1190KAREN5572497      16      False
10  11     leanna.abbott          aivlys24       8      False
11  12   milford.hubbard           hubbard       7       True

In [12]:
# Reading in the top 10000 passwords
common_passwords = pd.read_csv("10_million_password_list_top_10000.txt", header=None)

# Taking a look at the top 20
common_passwords.head(20)

            0
0      123456
1    password
2    12345678
3      qwerty
4   123456789
5       12345
6        1234
7      111111
8     1234567
9      dragon
10     123123
11   baseball
12     abc123
13   football
14     monkey
15    letmein
16     696969
17     shadow
18     master
19     666666

In [13]:
# Flagging the users with passwords that are common passwords
users['common_password'] = users['password'].isin(common_passwords)

# Counting and printing the number of users using common passwords
print(users['common_password'].sum())

# Taking a look at the 12 first rows
users.head(12)

0

    id         user_name          password  length  too_short  common_password
0    1    vance.jennings          joobheco       8      False            False
1    2    consuelo.eaton        0869347314      10      False            False
2    3   mitchel.perkins        fabypotter      10      False            False
3    4    odessa.vaughan         aharney88       9      False            False
4    5    araceli.wilder        acecdn3000      10      False            False
5    6  shawn.harrington           5278049       7       True            False
6    7        evelyn.gay            master       6       True            False
7    8       noreen.hale            murphy       6       True            False
8    9       gladys.ward           lwsves2       7       True            False
9   10   brant.zimmerman  1190KAREN5572497      16      False            False
10  11     leanna.abbott          aivlys24       8      False            False
11  12   milford.hubbard           hubbard       7       True            False

In [15]:
# Reading in a list of the 10000 most common words
words = pd.read_csv("google-10000-english.txt", header=None)

# Flagging the users with passwords that are common words
users['common_word'] = users['password'].str.lower().isin(words)

# Counting and printing the number of users using common words as passwords
print(users['common_word'].sum())

# Taking a look at the 12 first rows
users.head(12)

0

,id,user_name,password,length,too_short,common_password,common_word
0,1,vance.jennings,joobheco,8,False,False,False
1,2,consuelo.eaton,0869347314,10,False,False,False
2,3,mitchel.perkins,fabypotter,10,False,False,False
3,4,odessa.vaughan,aharney88,9,False,False,False
4,5,araceli.wilder,acecdn3000,10,False,False,False
5,6,shawn.harrington,5278049,7,True,False,False
6,7,evelyn.gay,master,6,True,False,False
7,8,noreen.hale,murphy,6,True,False,False
8,9,gladys.ward,lwsves2,7,True,False,False
9,10,brant.zimmerman,1190KAREN5572497,16,False,False,False
10,11,leanna.abbott,aivlys24,8,False,False,False
11,12,milford.hubbard,hubbard,7,True,False,False

In [16]:
# Extracting first and last names into their own columns
users['first_name'] = users['user_name'].str.extract(r'(^\w+)', expand=False)
users['last_name'] = users['user_name'].str.extract(r'(\w+$)', expand=False)

# Flagging the users with passwords that matches their names
users['uses_name'] = (users['password'] == users['first_name']) | (users['password'] == users['last_name'])
# Counting and printing the number of users using names as passwords
print(users['uses_name'].count())

# Taking a look at the 12 first rows
users.head(12)

982

,id,user_name,password,length,too_short,common_password,common_word,first_name,last_name,uses_name
0,1,vance.jennings,joobheco,8,False,False,False,vance,jennings,False
1,2,consuelo.eaton,0869347314,10,False,False,False,consuelo,eaton,False
2,3,mitchel.perkins,fabypotter,10,False,False,False,mitchel,perkins,False
3,4,odessa.vaughan,aharney88,9,False,False,False,odessa,vaughan,False
4,5,araceli.wilder,acecdn3000,10,False,False,False,araceli,wilder,False
5,6,shawn.harrington,5278049,7,True,False,False,shawn,harrington,False
6,7,evelyn.gay,master,6,True,False,False,evelyn,gay,False
7,8,noreen.hale,murphy,6,True,False,False,noreen,hale,False
8,9,gladys.ward,lwsves2,7,True,False,False,gladys,ward,False
9,10,brant.zimmerman,1190KAREN5572497,16,False,False,False,brant,zimmerman,False
10,11,leanna.abbott,aivlys24,8,False,False,False,leanna,abbott,False
11,12,milford.hubbard,hubbard,7,True,False,False,milford,hubbard,True

In [17]:
### Flagging the users with passwords with >= 4 repeats
users['too_many_repeats'] = users['password'].str.contains(r'(.)\1\1\1')

# Taking a look at the users with too many repeats
users.head(12)

/tmp/ipykernel_5066/880858671.py:2: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  users['too_many_repeats'] = users['password'].str.contains(r'(.)\1\1\1')

,id,user_name,password,length,too_short,common_password,common_word,first_name,last_name,uses_name,too_many_repeats
0,1,vance.jennings,joobheco,8,False,False,False,vance,jennings,False,False
1,2,consuelo.eaton,0869347314,10,False,False,False,consuelo,eaton,False,False
2,3,mitchel.perkins,fabypotter,10,False,False,False,mitchel,perkins,False,False
3,4,odessa.vaughan,aharney88,9,False,False,False,odessa,vaughan,False,False
4,5,araceli.wilder,acecdn3000,10,False,False,False,araceli,wilder,False,False
5,6,shawn.harrington,5278049,7,True,False,False,shawn,harrington,False,False
6,7,evelyn.gay,master,6,True,False,False,evelyn,gay,False,False
7,8,noreen.hale,murphy,6,True,False,False,noreen,hale,False,False
8,9,gladys.ward,lwsves2,7,True,False,False,gladys,ward,False,False
9,10,brant.zimmerman,1190KAREN5572497,16,False,False,False,brant,zimmerman,False,False
10,11,leanna.abbott,aivlys24,8,False,False,False,leanna,abbott,False,False
11,12,milford.hubbard,hubbard,7,True,False,False,milford,hubbard,True,False

In [18]:
# Flagging all passwords that are bad
users['bad_password'] = (users['too_short'])|(users['common_password'])|(users['common_word'])|(users['uses_name'])|(users['too_many_repeats'])

# Counting and printing the number of bad passwords
print(sum(users['bad_password']))

# Looking at the first 25 bad passwords
users[users['bad_password']==True]['password'].head(25)

383

5     5278049
6      master
7      murphy
8     lwsves2
11    hubbard
13     310356
15    oZ4k0QE
16    chelsea
17    zvc1939
18     nickgd
22    woodard
25      AJ9Da
26     ewokzs
28    YyGjz8E
30       reid
34    jOYZBs8
38    wwewwf1
43     225377
45     NdZ7E6
47      CQB3Z
48      diffo
52    y8uM7D6
56    mikeloo
58     golden
59    apr2502
Name: password, dtype: object

In [19]:
# Enter a password that passes the NIST requirements
# PLEASE DO NOT USE AN EXISTING PASSWORD HERE
new_password = "test@2026"